name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16]

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # minimize exposure and prevent accidental pushes

    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies
      run: yarn
      env:
        YARN_ENABLE_SCRIPTS: 0 # disable postinstall scripts

    - name: Lint code
      run: yarn test:lint

    - name: Build plugin
      run: yarn build

    - name: Run tests
      run: |
        cd test
        yarn
        yarn add -D eslint
        yarn test
      env:
        YARN_CHECKSUM_BEHAVIOR: update
        YARN_ENABLE_IMMUTABLE_INSTALLS: 0

  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: test

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # minimize exposure and prevent accidental pushes

    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Install dependencies
      run: yarn
      env:
        YARN_ENABLE_SCRIPTS: 0 # disable postinstall scripts

    - name: Build plugin
      run: yarn build

    - name: Run semantic release
      run: yarn semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
